### ISSUE TITLE
BMP280 and BME280 Chip ID

### ISSUE THREAD

**Issue by satriabha** [ciastkolog/BMP280_STM32#1]
Where can i find BMP280 and BME280 Chip ID? because there is no BMP280 or BME280 Chip ID written in datasheet. You write in your program that BMP280 Chip ID is 0x58 and BME280 Chip ID is 0x60.
Thank you

**Comment by ciastkolog** [comment]
You can find it on page 24 BMP280 datasheet and page 25 BMP280 datasheet.
